# Generated by Django 5.0.2 on 2024-04-26 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_transancciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombr_producto', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='cliente_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.clientes')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('id_cliente_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.cliente_producto')),
                ('id_transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tipo_transancciones')),
            ],
        ),
    ]
