# Generated by Django 5.0.2 on 2024-04-27 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_producto',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 23, 53, 51, 339458)),
        ),
        migrations.AddField(
            model_name='cliente_producto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente_producto',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 23, 53, 51, 339458)),
        ),
        migrations.AddField(
            model_name='clientes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 23, 53, 51, 339458)),
        ),
        migrations.AddField(
            model_name='clientes',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 23, 53, 51, 339458)),
        ),
        migrations.AddField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 23, 53, 51, 339458)),
        ),
        migrations.AddField(
            model_name='producto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 23, 53, 51, 339458)),
        ),
        migrations.AddField(
            model_name='tipo_transancciones',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 23, 53, 51, 339458)),
        ),
        migrations.AddField(
            model_name='tipo_transancciones',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipo_transancciones',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 23, 53, 51, 339458)),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 23, 53, 51, 339458)),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 23, 53, 51, 339458)),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='celular',
            field=models.CharField(max_length=20),
        ),
    ]
